### PR TITLE
Added my name to the team names file

### PR DESCRIPTION
**Pull request by sudoPom**
Added my name to the team_names.txt file so everyone knows which team I am on!

### CODE REVIEW

**Review by JayDwee — CHANGES_REQUESTED** [review]
image
Conflicting files need fixing before merging

**Comment by JayDwee** [comment]
Also please add a description to your PR, mentioning #1 (you can edit the PR message)

**Review by sudoPom — COMMENTED** [review]
Put my name to the very bottom of the file.

**Review by JayDwee — CHANGES_REQUESTED** [review]
Description is good, conflicts need fixing

image

**Review by JayDwee — APPROVED** [review]

**Pull request merged**
