### PR TITLE
Added Aqeel Little to team-members.txt

### PR DESCRIPTION
**Pull request by MoistBiscuits**
Added my name lol

### CODE REVIEW

**Review by JayDwee — APPROVED** [review]
In future use lowercase for branch name, but looks good otherwise!

**Comment by JayDwee** [comment]
@MoistBiscuits did you do it locally or on the website?

**Comment by MoistBiscuits** [comment]
Did it on website, cloning locally now

**Review by JayDwee — APPROVED** [review]
gj! Take a look at #2

**Pull request merged**
