### PR TITLE
Feat/jonathan add name

### PR DESCRIPTION
**Pull request by jplam123**
Moved from Emily's Fork to KoalaBot Fork #1

### CODE REVIEW

**Review by JayDwee — CHANGES_REQUESTED** [review]
Conflicting files found, take a look at resolving the issue

**Comment by JayDwee** [comment]
image

**Comment by JayDwee** [comment]
Also a better description in the PR should be used to describe what has changed. Mentioning #1 is a good idea

**Comment by jplam123** [comment]
> Also a better description in the PR should be used to describe what has changed. Mentioning #1 is a good idea

Thanks, I'll bear that in mind for the future. Merge conflicts should be resolved now.

**Review by JayDwee — APPROVED** [review]

**Pull request merged**
